app:
  version: "1.2.3"
  mode: "production"
  port: "9090"
  logpath: "/var/log/myapp"
  logfile: "server.log"
  ukey: "my-ukey"
  vtoken: "secure-token"
  salt: "random-salt"

metric:
  user: "admin"
  password: "sshhsuuwgwhysgs"

jwt:
  enabled: true
  secretkey: "x61Nmp@NUnV2Wn5S#HCD!p6"
  # in minutes
  expire: 10
  user: "wwxhyuyusj"
  header-key: "header-key"
  header-value: "6HdSWud6jkNUYEt8XrK6PuW"
  iss: "hls-key-server"
  aud: "hls-key-api"
