basePath: /
definitions:
  routes.ResponseHealthCheck:
    properties:
      Status:
        type: string
      recv_time:
        type: string
      recv_time_utc:
        type: string
    type: object
host: localhost:9090
info:
  contact: {}
  description: This is the API documentation for HLS Key Server.
  title: HLS Key Server API
  version: "1.0"
paths:
  /api/v1/auth/token:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Generates a JWT token if the username and custom header are valid
      parameters:
      - description: Username
        in: formData
        name: username
        required: true
        type: string
      - description: Custom authentication header
        in: header
        name: header-key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: JWT token
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Generate auth token
      tags:
      - Auth
  /healthz:
    get:
      description: Returns OK if the service is healthy
      responses:
        "200":
          description: Health check response
          schema:
            $ref: '#/definitions/routes.ResponseHealthCheck'
      summary: Check health status
      tags:
      - health
swagger: "2.0"
